# Generated by Django 2.2.6 on 2019-11-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
